"""add balance, rank && inventory columns to users table

Revision ID: ece55c4e150b
Revises: f42532e86529
Create Date: 2026-01-29 19:23:42.040249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece55c4e150b'
down_revision: Union[str, Sequence[str], None] = 'f42532e86529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('rank', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('inventory', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'inventory')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
